export const properties = [
  {
    id: 1,
    name: 'Apartments at Palm Bay',
    location: 'Palm Bay FL',
    image: '1-Apartmets-at-Palm-Bay.jpg',
    imageMobile: '1-Apartmets-at-Palm-Bay.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'apartments-at-palm-bay',
    description: 'Five minutes from The Avenue Viera mall for shopping, dining, and entertainment. The USSA Space Coast Stadium and Duran Golf Club are within two miles. Cocoa Village is a 20-minute drive, home to boutique shopping and weekend markets. This is new residential community with 120 units featuring luxury amenities including a resort style pool & Clubhouse area.',
    size: 120,
    unit: 'units + commercial space ',
    details: [
      '3-story apartment walk up'
    ],
    gallery: [
      'Apartments-at-Palm-Bay-1.jpg',
      'Apartments-at-Palm-Bay-2.jpg',
      'Apartments-at-Palm-Bay-3.jpg',
      'Apartments-at-Palm-Bay-4.jpg',
      'Apartments-at-Palm-Bay-5.jpg',
      'Apartments-at-Palm-Bay-6.jpg',
    ],
    type: 'Multifamily',
  },
  {
    id: 2,
    name: 'Magnolia Spring Hill',
    location: 'Spring Hill FL',
    image: '2-Crela-Spring-Hill.jpg',
    imageMobile: '2-Crela-Spring-Hill.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'magnolia-at-spring-hill',
    description: "Coming soon to Florida's West Coast is Magnolia at Spring Hill. A Residential property located within a short drive from Tampa Bay.  A new residential townhome community with 162 units featuring luxury amenities including a resort style pool & Clubhouse area.",
    size: 162,
    unit: 'Townhomes',
    details: [
      'Townhomes'
    ],
    gallery: [
      'Crela-Spring-Hill-5.jpg',
      'Crela-Spring-Hill-1.jpg',
      'Crela-Spring-Hill-2.jpg',
      'Crela-Spring-Hill-3.jpg',
      'Crela-Spring-Hill-4.jpg',
      'Crela-Spring-Hill-6.jpg',
    ],
    type: 'Multifamily',
  },
  {
    id: 3,
    name: 'Magnolia at Lake Hamilton',
    location: 'Winter Haven FL',
    image: '3-Cottages-at-Lake-Hamilton.jpg',
    imageMobile: '3-Cottages-at-Lake-Hamilton.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'magnolia-at-lake-hamilton',
    description: 'Coming soon to Central Florida is Magnolia at Lake Hamilton. A Residential property near Lego Land.  A new residential community with 200 units featuring luxury amenities including a resort style pool & Clubhouse area.',
    size: 200,
    unit: 'units',
    details: [
      'Cottages and Apartments'
    ],
    gallery: [
      'Cottages-at-Lake-Hamilton-1.jpg',
      'Cottages-at-Lake-Hamilton-2.jpg',
      'Cottages-at-Lake-Hamilton-3.jpg',
    ],
    type: 'Multifamily',
  },
  {
    id: 4,
    name: 'Magnolia at Powell',
    location: 'Wildwood FL',
    image: '4-Magnolia-at-Powell.jpg',
    imageMobile: '4-Magnolia-at-Powell.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'magnolia-at-powell',
    description: 'Coming soon to Central Florida is Magnolia at Powell. Residential property adjacent to the villages.  A new residential townhome community with 132 units featuring luxury amenities including a resort style pool & Clubhouse area.',
    size: 132,
    unit: 'units',
    details: [
      'Apartments',
      'Townhomes',
    ],
    gallery: [
      'Magnolia-at-Powell-1.jpg',
      'Magnolia-at-Powell-2.jpg',
      'Magnolia-at-Powell-3.jpg',
      'Magnolia-at-Powell-4.jpg',
      'Magnolia-at-Powell-5.jpg',
      'Magnolia-at-Powell-6.jpg',
    ],
    type: 'Multifamily',
  },
  {
    id: 5,
    name: 'Storage at Powell a Life Storage Facility',
    location: 'Wildwood FL',
    image: '5-Storage-at-Powell.jpg',
    imageMobile: '5-Storage-at-Powell.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'storage-at-powell',
    description: 'Coming soon to Central Florida is a Self Storage facility at Powell.  A Life Storage branded facility with 900+ storage units.',
    size: '100,000',
    unit: 'Sq Ft self-storage facility',
    details: [
      '900+ Storage units'
    ],
    gallery: [
      'Storage-at-Powell-1.jpg',
      'Storage-at-Powell-2.jpg',
      'Storage-at-Powell-3.jpg',
      'Storage-at-Powell-4.jpg',
      'Storage-at-Powell-5.jpg',
    ],
    type: 'Self-Storage',
  },
  {
    id: 6,
    name: 'Solamar Wildwood',
    location: 'Wildwood FL',
    image: '6-Solamar-Wildwood.jpg',
    imageMobile: '6-Solamar-Wildwood.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'solamar-wildwood',
    description: 'Solamar Wildwood is a new residential rental community with a mixture of 248 Villas and Townhomes located in Wildwood, FL near the Villages! This project broke ground  Spring 2022. The property will feature both villas and townhomes with luxury amenities including a resort style pool & clubhouse area, Kids Play area, Dog Park & Dog Wash station as well as a BBQ Area and Gazebos for residents to enjoy the beautiful year-round Florida weather!',
    size: 243,
    unit: 'units',
    details: [
      'Villas',
      'Cottages',
      'Townhomes',
    ],
    gallery: [
      'Solamar-Wildwood-1.jpg',
      'Solamar-Wildwood-2.jpg',
      'Solamar-Wildwood-3.jpg',
      'Solamar-Wildwood-4.jpg',
    ],
    type: 'Multifamily',
  },
  {
    id: 7,
    name: 'Solamar Kissimmee (Old vineland Road)',
    location: 'Kissimmee FL',
    image: '7-Solamar-Kissimmee.jpg',
    imageMobile: '7-Solamar-Kissimmee.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'solamar-kissimmee',
    description: 'The Solamar project is a new 210 residential townhome rental community located in Kissimmee near Orlando, the heart of Florida! This project was completed in early Spring 2023 . The property will feature private terraces with luxury amenities including a resort style pool & clubhouse area.',
    size: 210,
    unit: 'Townhomes',
    details: [
      'Townhomes'
    ],
    gallery: [
      'Solamar-Kissimmee-1.jpg',
      'Solamar-Kissimmee-2.jpg',
      'Solamar-Kissimmee-3.jpg',
      'Solamar-Kissimmee-4.jpg',
      'Solamar-Kissimmee-5.jpg',
    ],
    type: 'Multifamily',
  },
  {
    id: 8,
    name: 'Tru by Hilton Ft. Lauderdale Airport',
    location: 'Dania Beach FL',
    image: 'bg-Tru-by-Hilton.jpg',
    progress: 'Completed',
    status: 'completed',
    type: 'Hospitality',
    slug: 'tru-by-hilton',
    description: 'Tru by Hilton is the first Tru in Broward County. Recently completed in 2020, the 115-room hotel is conveniently situated near the Ft. Lauderdale Airport , Cruise Port, local shops, restaurants, and the Dania Beach Pier. There is also a 2,900 square foot lobby with areas for guests to work, play games, eat and lounge, along with a 24-7 "Eat & Sip".',
    size: 115,
    unit: 'room hotel',
    details: [
      'Fitness Center',
      'Business Center',
      'Event Hosting',
      'Valet Parking',
      'Outdoor Lounge',
    ],
    gallery: [
      'Tru-by-Hilton-1.jpg',
      'Tru-by-Hilton-2.jpg',
      'Tru-by-Hilton-3.jpg',
      'Tru-by-Hilton-4.jpg',
    ],
  },
  {
    id: 9,
    name: 'Melbourne Orlando International Airport Hotel',
    location: 'Orlando FL',
    slug: 'melbourne-orlando-international',
    image: 'bg-Melbourne-Orlando.jpg',
    progress: 'Completed',
    status: 'completed',
    type: 'Hospitality',
    description: 'One of our latest projects is a sophisticated five-story, four-star hotel featuring inspired guest-rooms and premium suites with energizing design and insightful in-room technology. Amenities include a roof top bar, coffee bar, outdoor swimming pool, multiple outdoor terraces, fitness studio, business center, and a large high-tech multi-space conference center.',
    size: 142,
    unit: 'room hotel',
    details: [
      'Rooftop Bar',
      'Coffee Bar',
      'Outdoor Swimming Pool',
      'Multiple Outdoor Terraces',
      'Fitness Studio',
      'Business Center',
      'High-Tech Conference Center',
    ],
    gallery: [
      'Melbourne-Orlando-1.jpg',
      'Melbourne-Orlando-2.jpg',
      'Melbourne-Orlando-3.jpg',
      'Melbourne-Orlando-4.jpg',
    ],
  },
  {
    id: 10,
    name: 'Hyatt Place',
    location: 'Melbourne FL',
    slug: 'hyatt-place',
    image: 'bg-Hyatt-Place.jpg',
    progress: 'Completed',
    status: 'completed',
    type: 'Hospitality',
    description: 'Conveniently located off I-95, Hyatt Place is an ideal base to experience the best of Florida’s Space Coast. A 106 room hotel completed in 2020. Close to the Florida Institute of Technology, catch a game at USSSA Space Coast Stadium, take a daytrip to Brevard Zoo, or discover Melbourne Beach.',
    size: 106,
    unit: 'room hotel',
    details: [
      'Pet Friendly',
      'Business Services',
      'Meeting Facilities',
      'Outdoor Pool and Lounge',
      'Laundry',
      'Fitness Center',
    ],
    gallery: [
      'Hyatt-Place-1.jpg',
      'Hyatt-Place-2.jpg',
      'Hyatt-Place-3.jpg',
    ],
  },
  {
    id: 11,
    name: 'Home2 Suites by Hilton',
    location: 'Melbourne FL',
    slug: 'home2-suites-by-hilton',
    image: 'bg-Home2-Suites-by-Hilton.jpg',
    progress: 'Completed',
    status: 'completed',
    type: 'Hospitality',
    description: 'Five minutes from The Avenue Viera mall for shopping, dining, and entertainment. The USSA Space Coast Stadium and Duran Golf Club are within two miles. Cocoa Village is a 20-minute drive, home to boutique shopping and weekend markets. This is an 87 room extended stay hotel completed in 2020.',
    size: 87,
    unit: 'room hotel',
    details: [
      'On-Site Restaurants',
      'Parking',
      'Outdoor Saltwater Pool',
      'Outdoor Lounge',
      'Pet Friendly',
      'Fitness Center',
      'Business Center',
    ],
    gallery: [
      'Home2-Suites-1.jpg',
      'Home2-Suites-2.jpg',
      'Home2-Suites-3.jpg',
    ],
  },
  {
    id: 12,
    name: 'Element by Marriot International',
    location: 'Orlando FL',
    slug: 'element-by-marriot-international',
    image: 'bg-Element-by-Marriot-International.jpg',
    progress: 'Completed',
    status: 'completed',
    type: 'Hospitality',
    description: 'Element Orlando International, a hotel committed to wellness and comfort. Located near SeaWorld Orlando, the Orange County Convention Center and shopping outlets. Move in Motion, with a 24-hour fitness center, offering everything you need to stay fit on the road. ',
    size: 144,
    unit: 'room hotel',
    details: [
      'Fitness Center',
      'Pool',
      'Pet Friendly',
      'Dry Cleaning',
      'Outdoor and Indoor Lounge',
    ],
    gallery: [
      'Element-by-Marriot-1.jpg',
      'Element-by-Marriot-2.jpg',
      'Element-by-Marriot-3.jpg',
    ],
  },
  {
    id: 13,
    name: 'Aloft Orlando by Marriot International',
    location: 'Orlando FL',
    slug: 'aloft-orlando',
    image: 'bg-Aloft-Orlando.jpg',
    progress: 'Completed',
    status: 'completed',
    type: 'Hospitality',
    description: 'A trendy and tech-forward hotel in Orlando, Florida, steps from SeaWorld Orlando. Offering easy-breezy access to major attractions, restaurants, museums, shops, theme parks and golf courses. This is a dual brand 288 room hotel completed in 2021.',
    size: 144,
    unit: 'room hotel',
    details: [
      'Fitness Center',
      'Pool',
      'Pet Friendly',
      'Dry Cleaning',
      'Outdoor and Indoor Lounge',
    ],
    gallery: [
      'Aloft-Orlando-1.jpg',
      'Aloft-Orlando-2.jpg',
      'Aloft-Orlando-3.jpg',
    ],
  },
]

export const propertiesMX = [
  {
    id: 'mx-1',
    name: 'Garden Condesa',
    location: 'Mexico City MX',
    image: 'bg-Garden-Condesa.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'garden-condesa',
    description: 'Garden Condesa, is a building defined by its green spaces and a modern atmosphere that is adapted for families and all types of residents.',
    size: 'TBA',
    unit: '',
    details: [
      '47 Luxury Condo Units',
      'BBQ Area',
      'Sky Lounge',
      'Lush Gardens',
      'Playroom',
      'Fire Pit',
    ],
    gallery: [
      'Garden-Condesa-1.jpg',
      'Garden-Condesa-2.jpg',
      'Garden-Condesa-3.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-2',
    name: 'MONTE CAMERÚN 50',
    location: 'Mexico City MX',
    image: 'bg-Monte-Camerun-50.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'monte-camerun-50',
    description: 'Offering quality and luxurious spaces under the best standards in structural engineering.',
    size: 'TBA',
    unit: '',
    details: [
    ],
    gallery: [
      'Monte-Camerun-1.jpg',
      'Monte-Camerun-2.jpg',
      'Monte-Camerun-3.jpg',
      'Monte-Camerun-4.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-3',
    name: 'Garden Polanco',
    location: 'Mexico City MX',
    image: 'bg-Garden-Polanco.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'garden-polanco',
    description: 'Garden Polanco is many travelers hotel of choice when visiting Mexico City. Providing an ideal mix of value, comfort and convenience, it offers an array of amenities designed for travelers all over the world.',
    size: 'TBA',
    unit: '',
    details: [
      'Fitness Center',
      'Bar and Restaurant',
      'Lounge',
      'Conference Facilities',
    ],
    gallery: [
      'Garden-Polanco-1.jpg',
      'Garden-Polanco-2.jpg',
      'Garden-Polanco-3.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-4',
    name: 'Concepción Beistegui',
    location: 'Mexico City MX',
    image: 'Concepcion-Beistegui.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'concepcion-beistegui',
    description: 'Concepción Beistegui 811 is located in Colonia del Valle, south of Mexico City, an area that has undergone multiple changes since its inception and which today stands out as one of the areas with greater development and infrastructure for communication, transportation and services of Mexico.',
    size: 'TBA',
    unit: '',
    details: [
      '74 Luxury Condo Units',
      'Enriched Neighborhood',
      'Near Large Shopping Center',
      'Close to local parks and cycle paths',
    ],
    gallery: [
      'Concepcion-Beistegui-1.jpg',
      'Concepcion-Beistegui-2.jpg',
      'Concepcion-Beistegui-3.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-5',
    name: 'Musset 222',
    location: 'Mexico City MX',
    image: 'Musset-222.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'musset-222',
    description: 'Exclusive development located in the heart of Polanco.',
    size: 'TBA',
    unit: '',
    details: [
    ],
    gallery: [
      'Musset-1.jpg',
      'Musset-2.jpg',
      'Musset-3.jpg',
      'Musset-4.jpg',
      'Musset-5.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-6',
    name: 'Tres Picos 97',
    location: 'Mexico City MX',
    image: 'Tres-Picos-97.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'tres-picos-97',
    description: 'Beautiful and luxurious furnished apartments, in a great area of ​​Mexico City.',
    size: 'TBA',
    unit: '',
    details: [
    ],
    gallery: [
      'Tres-Picos-1.jpg',
      'Tres-Picos-2.jpg',
      'Tres-Picos-3.jpg',
      'Tres-Picos-4.jpg',
      'Tres-Picos-5.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-7',
    name: 'Solón 337',
    location: 'Mexico City MX',
    image: 'Solon-337.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'solon-337',
    description: 'Garden Polanco is many travelers choice when visiting Mexico City. Providing an ideal mix of value, comfort and convenience, it offers an array of amenities designed for travelers all over the world.',
    size: '11',
    unit: 'apartments',
    details: [
    ],
    gallery: [
      'Solon-1.jpg',
      'Solon-2.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-8',
    name: 'Elysée 369',
    location: 'Mexico City MX',
    image: 'Elysee-369.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'elysee-369',
    description: 'In the heart of Polanco and on Campos Eliseos, one of the most traditional streets in the city, Elysée emerges, an exclusive residential project that combines a great location with the most spectacular views of the Bosque de Chapultepec.',
    size: '',
    unit: '',
    details: [
      '23 Luxury Condo Units',
      'Roof Garden',
      'Fitness Center',
      'Sky Lounge',
      'Pool & Jacuzzi',
      'Playroom',
    ],
    gallery: [
      'Elysee-1.jpg',
      'Elysee-2.jpg',
      'Elysee-3.jpg',
      'Elysee-4.jpg',
      'Elysee-5.jpg',
      'Elysee-6.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-9',
    name: 'E.A. Poe 335',
    location: 'Mexico City MX',
    image: 'E.A.-Poe-335.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'ea-poe-335',
    description: 'Beautiful apartment complex in Polanco, near Castelar Park.',
    size: '8',
    unit: 'apartments',
    details: [
    ],
    gallery: [
      'E.A.-Poe-335-1.jpg',
      'E.A.-Poe-335-2.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-10',
    name: 'Guanajuato 238',
    location: 'Mexico City MX',
    image: 'Guanajuato-238.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'guanajuato-238',
    description: 'Offering spacious apartments with extensive terraces and incredible private Roof Gardens, where you will enjoy pleasant conversations with friends, family or simply relax and read a good book. Set in the best location in Colonia Roma and enjoy its gastronomy, parks and architecture.',
    size: '',
    unit: '',
    details: [
      'Roof Garden',
      '24 hour surveillance',
      'Private surveillance',
      'Terrace',
    ],
    gallery: [
      'Guanajuato-1.jpg',
      'Guanajuato-2.jpg',
      'Guanajuato-3.jpg',
      'Guanajuato-4.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-11',
    name: 'San Antonio 95',
    location: 'Mexico City MX',
    image: 'San-Antonio-95.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'san-antonio-95',
    description: 'San Antonio, 95 has 78 luxury condo apartments distributed in 11 levels.',
    size: '78',
    unit: 'apartments',
    details: [
      'Fitness Center',
      'Playroom',
      'Lounge',
      'Roof Garden',
      '24/7 Security',
      'BBQ Area',
    ],
    gallery: [
      'San-Antonio-1.jpg',
      'San-Antonio-2.jpg',
      'San-Antonio-3.jpg',
    ],
    type: 'Residential',
  },
  {
    id: 'mx-12',
    name: 'Cholula 17',
    location: 'Mexico City MX',
    image: 'Cholula-17.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'cholula-17',
    description: 'Offering quality and warm spaces and finishes with functional and timeless architecture, creating pure and environmentally friendly spaces, under the best standards in structural engineering.',
    size: '',
    unit: '',
    details: [
      '18 Luxury Condos',
      'Near National Parks',
      'Security',
      'Recreational Spaces',
    ],
    gallery: [
      'Cholula-1.jpg',
      'Cholula-2.jpg',
      'Cholula-3.jpg',
      'Cholula-4.jpg',
      'Cholula-5.jpg',
    ],
    type: 'Residential',
  },
]